# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17651ad89a287f57469e9e01fa55a58a2f7b491f216ebed5c939fd9bc11e4f513fbc5eb333136a05e62a2e9aa04cf8b7ed30bcc48ffdba96d76fb965e5a42572

test:
  secret_key_base: e73796c1f21c7597533c5724366ee0d32dabb35d46fa8e362bb88c39b989cc5769558aa9b758b46d2159723f3dfb8135b9853e039522766e9e48e6c4673209dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
